version: '1.0'

services:
  mongo:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ~/mongo/data:/data/db

  auth-service:
    build: ./server-authentication
    container_name: auth-service
    ports:
      - '5555:5555'

  exp-service:
    build: ./server-experiment
    container_name: exp-service
    ports:
      - '5050:5050'
    depends_on:
      - auth-service

  emf-cloud-service:
    build: ./server-emf-cloud
    container_name: emf-cloud-service
    ports:
      - '8081:8081'

  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - '7001:7001'
    depends_on:
      - auth-service
      - exp-service

  nginx:
    image: nginx:latest
    container_name: nginx-servers
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - auth-service
      - exp-service
    restart: always
